### ISSUE TITLE
Remove babel polyfill from JS bundle

### ISSUE THREAD

**Issue by rej156** [fortmatic/EthDenver-2019#1]
Can only be instantiated once on the environment leading to errors when integrating on projects with babel preset env
Also really heavy, pollutes global too

**Comment by mqklin** [comment]
@rej156 you can use `import '@babel/polyfill/noConflict';` as a workaround

**Comment by Ethella** [comment]
fortmatic@0.5.0 is released. Polyfill plugin is removed from SDK. Fill free to try it out

**Comment by rej156** [comment]
Legends!

**Comment by rej156** [comment]
Feel free to close

**Comment by Mulyadifamba19651982** [comment]
Goods

**Comment by FYJen** [comment]
The Polyfill plugin issue has been fixed. Closing.
