### ISSUE TITLE
Fortmatic form close callback

### ISSUE THREAD

**Issue by mqklin** [fortmatic/EthDenver-2019#2]
Is there any type of close callback?

**Comment by FYJen** [comment]
@mqklin: please take a look at our [SDK error handling](https://docs.fortmatic.com/web3-integration/sdk-error-handling). We handle the close callback on a case by case basis.

Please let us know if you have any other question. We are on [Discord](https://discordapp.com/invite/JqrDbRB), or you can send us an email (support@fortmatic.com)
