### ISSUE TITLE
Typing 8-digit code doesn't work

### ISSUE THREAD

**Issue by mqklin** [fortmatic/EthDenver-2019#4]
Can't type any digits on my Sony Xperia Z3 (typing phone number works btw)

**Comment by Dizigen** [comment]
dup of https://github.com/fortmatic/x/issues/427

**Comment by Dizigen** [comment]
we are tracking this issue internally.

**Comment by Mulyadifamba19651982** [comment]
Goods

**Comment by FYJen** [comment]
Closing this ticket as Won't Fix.
